### ISSUE TITLE
Possible bug in FileReader

### ISSUE THREAD

**Issue by vladimirvrabely** [ndokter/dsmr_parser#101]
Hi,

When I use`FileReader`, the telegrams are successfully parsed and checksummed but the loop doesn't stop after reading the whole file. Is there something wrong with my data file? Is this the intended behaviour? (I have `Python 3.9.10` and `dsmr-parser==0.32`)

If it isn't, I think [the lines](https://github.com/ndokter/dsmr_parser/blob/master/dsmr_parser/clients/filereader.py#L65) should be probably changed to something
```python       
 while True:
    data = file_handle.readline()
    if not data:
        break
    s = data.decode()
    self.telegram_buffer.append(s)
```

**Comment by ndokter** [comment]
I think you are right. I've been testing a bit with it and make a PR with your proposal:
https://github.com/ndokter/dsmr_parser/pull/102
