### ISSUE TITLE
Replace telegram dictionary with a Telegram object

### ISSUE THREAD

**Issue by ndokter** [ndokter/dsmr_parser#11]
After parsing a telegram in the form of a dict is returned. The values can be retrieved using defined constants.

It would probably be nicer to have a specific Telegram object that has some handy dynamic properties to retrieve the values with. The raw data will still be available.

Will try to maintain backwards compatibility (for now) by implementing __getitem__ so most usages will remain intact.

Edit: repurposed this ticket to make it more concrete

**Comment by dennissiemensma** [comment]
Well, I can vouch for unittests/black box tests for this API.

This will allow you to easily detect non-backwards compatible changes in future releases, and highlight/warn people about that in future releases. 
Offcourse, this is dispite the fact that people **should** test any integration (or upgrade) of your library, before using it blindly anyway.

**Comment by ndokter** [comment]
A true telegram object has been added: https://github.com/ndokter/dsmr_parser/pull/40
