### ISSUE TITLE
typo in readme example

### ISSUE THREAD

**Issue by Michael-Yongshi** [ndokter/dsmr_parser#123]
See fix in
[https://github.com/Michael-Yongshi/dsmr_parser/blob/master/README.rst](https://github.com/Michael-Yongshi/dsmr_parser/blob/master/README.rst)

```python
 # Using the active tariff to determine the electricity being used and
 # delivered for the right tariff.
 active_tariff = telegram[obis_references.ELECTRICITY_ACTIVE_TARIFF]
 active_tariff = int(tariff.value)
```

see that the int(tariff.value) is referring to a non-existing variable 'tariff'

**Comment by ndokter** [comment]
Thank you for bringing this up. I will rewrite parts of those documentation in PR #121
