### ISSUE TITLE
v1.4.1 seems not to be in HomeAssistant >2024.7.1

### ISSUE THREAD

**Issue by Boemeltrein** [ndokter/dsmr_parser#161]
Sorry if this is the wrong place to ask, but Github is relative new.
Version 1.4.1 seems not to be included in the latest HomeAssistant release.
My log is overflowing with the timezone issues.

The release is mentioned here:
https://github.com/ndokter/dsmr_parser/releases
Somehow not showing as latests?

Is it correct is it not included in home assistant yet?
Here is a mentioning part the library needs to be bumbed?
https://github.com/home-assistant/core/issues/118919

**Comment by Boemeltrein** [comment]
hmm never mind, maybe it is gone now and only 1 message. Will keep tracking it going days...

**Comment by dupondje** [comment]
HA 2024.8.x has 1.4.2 now.
