### ISSUE TITLE
New release for serial changes

### ISSUE THREAD

**Issue by elupus** [ndokter/dsmr_parser#162]
Hi

Just updating the lib in HA (https://github.com/home-assistant/core/pull/121929) . Would be nice to get the new serial lib changes in directly.

Could we get a 1.4.2 release?

**Comment by ndokter** [comment]
Hi, i've made a new release:
https://github.com/ndokter/dsmr_parser/releases/tag/v1.4.2

https://pypi.org/project/dsmr-parser/

**Comment by elupus** [comment]
Thanks!

**Comment by elupus** [comment]
Btw. The new way with string attributes is problematic. It becomes hard to detect breaking changes when we have no fixed symbols, only arbitrary strings.
