### ISSUE TITLE
install problem on my Zotac woth hassio

### ISSUE THREAD

**Issue by ronniebee** [ndokter/dsmr_parser#42]
I get the foloowing message on my SSh:

Collecting dsmr-parser
Using cached https://files.pythonhosted.org/packages/9e/d0/eb5c275d7b293f3fb6a754e017a79e3e929bf32c14e920e2a7278edfd04a/dsmr-parser-0.14.tar.gz
Collecting pyserial<4,>=3 (from dsmr-parser)
Downloading https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl (193kB)
100% |████████████████████████████████| 194kB 1.5MB/s
Collecting pyserial-asyncio<1 (from dsmr-parser)
Using cached https://files.pythonhosted.org/packages/41/3f/e26f71269cbc0890a527a736d9afc5c0d5838a2c188be680558d635b7dc2/pyserial-asyncio-0.4.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-build-6hhyQU/pyserial-asyncio/setup.py", line 15, in
raise RuntimeError("pyserial-asyncio requires at least Python 3.4")
RuntimeError: pyserial-asyncio requires at least Python 3.4

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6hhyQU/pyserial-asyncio/

What do I need to do to resolve this? (yes I'm a newbee ... :-) )

**Comment by ndokter** [comment]
Thank you for reaching out. It seems that you are using Python 3, but a version older than 3.4 which is not supported
