### ISSUE TITLE
Probleem installeren

### ISSUE THREAD

**Issue by ronniebee** [ndokter/dsmr_parser#46]
Hoi Nigel,

Ik wil de parser in docker installeren maar krijg de melding:

![image](https://user-images.githubusercontent.com/7029899/71544590-b6a4e000-2981-11ea-86d2-d517c3fa6b78.png)

Wat te doen?

**Comment by ndokter** [comment]
dsmr-parser is a Python library and has to be installed using pip. 'apt' is for system (Ubuntu/Debian) packages

**Comment by ronniebee** [comment]
When i Use pip it states:

![image](https://user-images.githubusercontent.com/7029899/71544629-4b0f4280-2982-11ea-9670-59c43e9ee6a7.png)

**Comment by ndokter** [comment]
pip can be installed using apt as the error indicates

**Comment by ronniebee** [comment]
thx! it's working!
