### ISSUE TITLE
Limit information-overflow (to HASS database)

### ISSUE THREAD

**Issue by tbressers** [ndokter/dsmr_parser#50]
Feature request

Would it be possible to add a configuration item to reduce the maximum generated amount of data per minute (or hour)? My home-assistant database is flooded, and there seems no good way to prevent that (hence, the recorder purging doesn't seem to do much / enough)

**Comment by ndokter** [comment]
I should check the implementation in home-assistent. This change makes a little bit more sense in HA at first glance.

**Comment by tbressers** [comment]
Thank you... I will do so

Op vr 28 feb. 2020 om 11:06 schreef Nigel Dokter <notifications@github.com>:

**Comment by ndokter** [comment]
I could also be a feature in the serial reader though, but im not sure if HA uses that (i dont think so)

**Comment by tbressers** [comment]
Somehow it does feel like something one would like to solve as low-level as
possible... but I don't know the architecture enough to determine where
such an implementation would fit best.



Op vr 28 feb. 2020 om 11:48 schreef Nigel Dokter <notifications@github.com>:

**Comment by ndokter** [comment]
Yeah it should be implemented somewhere in https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/dsmr/sensor.py
