### ISSUE TITLE
Can this be "released" via git tags?

### ISSUE THREAD

**Issue by SEJeff** [ndokter/dsmr_parser#6]
This makes it much easier to know what is contained inside "version 0.3" for instance. It is also easier for packaging things up.

Thanks!

**Comment by ndokter** [comment]
Thanks for you feedback. This will make it a lot easier indeed and i will release subsequent versions using it.

**Comment by SEJeff** [comment]
Thanks!

**Comment by ndokter** [comment]
I've added them retroactively as its not a lot of effort to do so :)
